Tweaked Docs Page
Bay-Valley-Tech-Code-Academy/UI-Components-Kit pull request #28
Opened 2024-08-30 22:19 UTC by davidxiong117

Added A LOT of changes to the docs page. Please review it thoroughly.

This is still a work in progress. Please give me some feedback.

Added a temporary FAQ section, am currently working on it to make it more realistic.

2024-08-30 22:29 UTC, missile720 requested changes
Looks good! I think the side navigation for the document should stay in place that way users can still use the document navigation to go to each section of the page. For the FAQ section maybe give it more spacing between the questions and response. Its very close together to each other.

2024-08-30 22:59 UTC, kimbencinas approved these changes

2024-09-04 16:31 UTC, davidxiong117 commented
Addressed the issues brought up by missile,
![Capture](https://github.com/user-attachments/assets/b4f9988f-df51-4e3a-860e-ac3e9e7ee17f)

2024-09-04 16:32 UTC, missile720 approved these changes
Looks good!

2024-09-04 16:32 UTC, merged